version: "1"
services:
  postgres:
    container_name: shop_db
    image: postgres:11.1-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
  redis:
    image: "redis:5.0.3"
    command: redis-server --requirepass 333
    container_name: redis
    networks:
      - net
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - "./redis:/usr/local/etc/redis"
  rabbitmq:
    image: "rabbitmq:3.8.2-management"
    container_name: rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: 5m
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - "5672"
networks:
  net:
    driver: bridge
